Architecture reveiw
kgamora/cli-itmo-sd-2023 pull request #1
Opened 2023-02-17 15:44 UTC by Nikolai-SE

Проведено исправление некоторых ошибок в описании архитектуры

2023-02-18 14:26 UTC, kgamora approved these changes

2023-02-18 14:26 UTC, kgamora commented on architecture/README.md
> +1. Чтение входных данных до символа переноса строки.
Опять же по большому счёту оно не всегда читает, оно ожидает ввода, и в случае наличия ввода уже происходят все описанные ниже действия.

2023-02-18 18:54 UTC, Nikolai-SE commented on architecture/README.md
> +1. Чтение входных данных до символа переноса строки.
А если будут введены несколько пробелов? Это получается надо отслеживать на этапе чтения входной строки - а это уже лексинг - в зоне ответственности Lexer-a.

2023-02-19 16:37 UTC, kgamora commented on architecture/README.md
> +1. Чтение входных данных до символа переноса строки.
о'кей, предлагаю использовать архитектуру splitter - substitutor - lexer

2023-02-19 17:09 UTC, kgamora requested changes
В целом мне нравится описание подстановщика и можно всё это реализовать и так, но тогда нам придётся дублировать почти ту же логику в парсере, т.к. Executable хочет иметь на входе именно лексемы, и штуки вида `e"xi"t` он уже не скушает (проверено на subprocess.run, который мы и будем использовать). Поэтому предлагается создать какой-то утилитарный класс Splitter, который поможет нам во всём этом

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> -## Запуск, интерфейс
Не понимаю, чем подразделы-то не понравились
Мне кажется, категоризация сущностей системы по их функционалу удобнее как документация чем сплошняковое перечисление названий классов и их функицонала

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +#### Точкой входа в программу является метод `run` класса `Application`.
Это статический или динамический метод?

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +2. Разбиение входной строки по символам | ( `pipeline` ). Получение массива строк.
я бы и символ пайпа выделил `|`

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +В `contextManager` сохраняются переменные окружения, добавленные пользователем во время сеанса использования программного продукта. В методе `run` поспедовательно выполняются следующие действия:
Программный продукт включает тестирование, сопровождение, документирование и обобщение. Лучше не нарываться и назвать это `Программой`

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +4. Подстановка переменных из контекста приложения в каждую из полученных строк с помощью `Substituter`.
В таком случае Substituter будет заниматься не только подстановкой, но и нахождением этих подстрок внутри того что оказалось между пайпами. Правила для такого поиска и подстановки достаточно нетривиальны и нагружать одну сущность двумя задачами - не ок. Для этого лучше один раз написать все необходимые нам разбиения и потом использовать их интерфейс в зависимости от задачи.

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +7. Последовательное исполнение экземпляров `Executable` с помощью `Executor`. При наличии | ( `pipeline` )  происходит  передача вывода предыдущих экземпляров `Executable` на ввод последующим.
то же самое про выделение символа пайпа

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +В `contextManager` сохраняются переменные окружения, добавленные пользователем во время сеанса использования программного продукта. В методе `run` поспедовательно выполняются следующие действия:
Не только во время сеанса - системные переменные тоже должны быть там

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +Класс `Substitution` имеет метод `substitute`, принимающий строку и выполняющий подстановку следующие действия:
подстановку следующие действия (опечатка)

2023-02-19 17:09 UTC, kgamora commented on architecture/README.md
> +2. Если вторая лексема **соответствует** символу `=`, то создается соответствующий наследник класса `Executable`. Остальные лексемы передаются в качестве аргументов.
а что если первая лексема соответствует названию встроенной команды, а вторая соответствует символу `=`? надо приоритет тогда задавать

2023-02-19 17:24 UTC, Nikolai-SE commented on architecture/README.md
> +В `contextManager` сохраняются переменные окружения, добавленные пользователем во время сеанса использования программного продукта. В методе `run` поспедовательно выполняются следующие действия:
Ok

2023-02-19 17:25 UTC, Nikolai-SE commented on architecture/README.md
> +2. Разбиение входной строки по символам | ( `pipeline` ). Получение массива строк.
Ok

2023-02-19 17:26 UTC, Nikolai-SE commented on architecture/README.md
> +#### Точкой входа в программу является метод `run` класса `Application`.
Зависит от ЯП, детали реализации

2023-02-19 17:27 UTC, Nikolai-SE commented on architecture/README.md
> +2. Разбиение входной строки по символам | ( `pipeline` ). Получение массива строк.
По пайпам происходит деление на Массив строк. Пайпы после этого не нужны

2023-02-19 17:29 UTC, Nikolai-SE commented on architecture/README.md
> +4. Подстановка переменных из контекста приложения в каждую из полученных строк с помощью `Substituter`.
Поиск и подстановка происходят за один проход. Алгоритм поиска описан.

2023-02-19 17:29 UTC, Nikolai-SE commented on architecture/README.md
> +В `contextManager` сохраняются переменные окружения, добавленные пользователем во время сеанса использования программного продукта. В методе `run` поспедовательно выполняются следующие действия:
Ok

2023-02-19 18:01 UTC, Nikolai-SE commented on architecture/README.md
> +4. Подстановка переменных из контекста приложения в каждую из полученных строк с помощью `Substituter`.
Если отделить логику поиска заменяемых подстрок от их замены на другие подстроки, то можно нарушить принцип Low Coupling High Cohesion. Класс должен делать одну _бизнес_ задачу. Поиск и замена подстроки на другую это задачи программирования.

2023-02-19 18:03 UTC, Nikolai-SE commented on architecture/README.md
> +7. Последовательное исполнение экземпляров `Executable` с помощью `Executor`. При наличии | ( `pipeline` )  происходит  передача вывода предыдущих экземпляров `Executable` на ввод последующим.
Да, тут про pipeline не уместно. Забыл убрать, спасибо

2023-02-19 18:05 UTC, Nikolai-SE commented on architecture/README.md
> +Класс `Substitution` имеет метод `substitute`, принимающий строку и выполняющий подстановку следующие действия:
Спасибо

2023-02-19 18:08 UTC, Nikolai-SE commented on architecture/README.md
> +2. Если вторая лексема **соответствует** символу `=`, то создается соответствующий наследник класса `Executable`. Остальные лексемы передаются в качестве аргументов.
Предлагаю присваиванию дать приоритет выше.
Поднял его в первый пункт

2023-02-19 20:28 UTC, merged