cd, ls
kgamora/cli-itmo-sd-2023 pull request #10
Opened 2023-03-31 17:37 UTC by OldKrab

2023-03-31 18:32 UTC, bachisheo commented
Архитектура приложения хорошая. На схеме отражены все используемые компоненты и связи между ними понятные.
Файлы проекта декомпозированы. Добавление новой функциональности не составляет большого труда. Текущая реализация соответсвует архитектуре.

Код проекта чистый, с понятными комментариями. По возможности используются возможности типизации для минимизации ошибок. Классы и переменные понятно именованы. Сами файлы также понятно называны, что делет разработку и чтение кода приятным. Приложение покрыто тестами. Подключен линтер. В проекте есть requirements.txt и все зависимости зафиксированы.

Замечаний по архитектоуре нет. Замечаний по работе приложения нет. Отмечаем возможность цветного вывода. Это круто)

Из небольших недоработок по проекту:
В Readme не указана требуемая для запуска версия python. При этом требуется относительно свежая 3.10.

Много сторонних зависимостей. Возможно какие-то из них не используются, или используется только какая-то тривиальная функциональность, которую можно было бы исользовать напрямую.

На Windows не проходит тест test_global_executable.py. Он завязан на команду ls. Но вообще это не тривиальная задача - написать универсальный тест для запуска сторонней команды. Думаю в том или ином виде у всех в этом месте будут ошибки.

В комментариях ко всем реализуемым комммандам есть фраза "work like command in standard Linux distros", что смущает в приложении, которое должно быть кроссплатформенным.

Так же не очень удобно, что документация разбросана по .md файлам в разных папках.

2023-04-08 22:00 UTC, uncerso requested changes
Занятно, вы похвалили за requirements.txt, но не написали про то, что без подсматривания в CI непонятно, как этим всем пользоваться. :)

Команда `cd` без аргумента тоже должна поддерживаться, и отправлять она должна в домашнюю папку пользователя.

В тестах для cd нужно ещё добавить "cd без аргументов".

Внезапно на ls всё ещё вызывается внешняя команда.

2023-04-10 18:55 UTC, OldKrab commented
> Команда `cd` без аргумента тоже должна поддерживаться, и отправлять она должна в домашнюю папку пользователя.
> 
> В тестах для cd нужно ещё добавить "cd без аргументов".

Готово

> Внезапно на ls всё ещё вызывается внешняя команда.

Это в test_global_executable.py? Ну это хороший вариант, который работает и на линуксе, и на винде.

2023-04-16 15:12 UTC, uncerso requested changes
>> Внезапно на ls всё ещё вызывается внешняя команда.

В том-то и проблема, что любой ls:
![image](https://user-images.githubusercontent.com/25592720/232322170-c69da6b5-d97d-4cfe-a7e0-cf68c161ae09.png)

2023-04-16 16:03 UTC, OldKrab commented
> > > Внезапно на ls всё ещё вызывается внешняя команда.
> 
> В том-то и проблема, что любой ls: ![image](https://user-images.githubusercontent.com/25592720/232322170-c69da6b5-d97d-4cfe-a7e0-cf68c161ae09.png)

Ааа, ну да, забыли добавить ее в список всех команд) Исправил.

2023-06-17 11:27 UTC, uncerso requested changes
ls игнорирует полностью свои аргументы.

2023-06-18 17:04 UTC, OldKrab commented
> ls игнорирует полностью свои аргументы.

Исправил

2023-06-25 08:05 UTC, uncerso approved these changes
Обычный `ls <файл>` возвращает этот самый файл, в то время как ваш ошибку пишет.
А остальном ок, зачёл.

2025-08-21 19:19 UTC, closed without merging